### ISSUE TITLE
StackView Issue

### ISSUE THREAD

**Issue by kuraydev** [sunilsharma08/IGCMenu#23]
Hello, 
I love using this library, thank you so much ! :) 

It is working really good but when i put my button inside a StackView, its menuSuperView not working correctly. It could be my fault but i couldn't solve it :) 

I hope you can find a way for me :) 

Thank you!

**Comment by sunilsharma08** [comment]
Sorry for replying late. Currently this library does not support StackView. To make it work with StackView you have to pass stackview refernce in `menuSuperView` property and you have to also make sure that stackview cover whole screen.
