### ISSUE TITLE
About Background Color Changes

### ISSUE THREAD

**Issue by kuraydev** [sunilsharma08/IGCMenu#24]
Hello sir,
I love using this library :) Thank you so much !

I need to change the color when user tapped one of the menu items. I can do that with a silly solution. Can you suggest me a good solution for changing background colors when user select one of the menu items ? 

Thank you :)

**Comment by sunilsharma08** [comment]
Hi,
Thanks for your appreciation.
I am little confused whether you want to change menu **button** background color or menu background that covers the whole screen.

**Comment by kuraydev** [comment]
I want to change the menu button background color, not the whole screen

**Comment by sunilsharma08** [comment]
Currently, it does not support updating menu button background color update. I have created a new branch [updateButtonBackground](https://github.com/sunilsharma08/IGCMenu/tree/updateButtonBackground) to add this feature. Added new method `-(void)updateButtonBackground:(NSInteger)atIndex withColor:(UIColor *) newColor`to update button background color in IGCMenu class at bottom. To update tapped button background color you can call `updateButtonBackground` method with tapped button index and new color in delegate method `-(void)igcMenuSelected:(NSString *)selectedMenuName atIndex:(NSInteger)index`.

**Comment by kuraydev** [comment]
Thank you so much, I'm gonna try it :)
