### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by HackShitUp** [sunilsharma08/IGCMenu#9]
So I got everything to work (from last time), but I've noticed whenever I use your framework, my device heats up. Like it really heats the fuck up -  it gets really fucking hot. I'm thinking there's a memory leak? I'll try to look into it to see what's going on.

**Comment by sunilsharma08** [comment]
Can you share little more details like any particular os ,device or any other thing
I checked in xcode Leaks instruments but nothing suspicious found.This library is used in app called [Omveria](https://itunes.apple.com/us/app/omveria/id972598592?mt=8) and  this problem is never observed.

**Comment by HackShitUp** [comment]
Interesting...
• iPhone 6
• iOS 10

**Comment by sunilsharma08** [comment]
Is the same thing happening with example project ?
